### ISSUE TITLE
Upgrade jwt to next release

### ISSUE THREAD

**Issue by misilot** [Born-Digital-US/islandora_install_profile_demo#22]
Update drupal/jwt to https://www.drupal.org/project/jwt/releases/8.x-1.0-rc2

https://github.com/Islandora-Devops/islandora_install_profile_demo/blob/2b5953b9da6ae2ec61f9913c7f8c9572e477c876/composer.json#L114

Which brings in correct validation for HMAC keys https://www.drupal.org/project/jwt/issues/3257542, and php8.1 errors (see release notes above)

**Comment by noahwsmith** [comment]
Thanks for the reminder. I took the liberty of just doing this directly since we have tested this extensively at Born-Digital:
https://github.com/Islandora-Devops/islandora_install_profile_demo/commit/e7db6f691240627e143a272d882bcf0c6ce30e61
