### ISSUE TITLE
Browse Collections won't show collections.

### ISSUE THREAD

**Issue by rosiel** [Born-Digital-US/islandora_install_profile_demo#27]
The home_page_featured_collections view requires 'http://purl.org/dc/dcmitype/Collection#Model' in the URI of the term in Field Model.

The "Collection" term that lives in Islandora Models has URI http://purl.org/dc/dcmitype/Collection

When changed, collections (having "Collection" under both fields because they're both still mandatory #11 ) show up.

<img width="1877" alt="Screen Shot 2022-08-31 at 1 13 09 PM" src="https://user-images.githubusercontent.com/1943338/187729088-3fea67bc-16e5-497c-82be-18a4dd575c22.png">

While we're at it:
- This is not a "Featured Collections" view, it is an "all collections" view, the name (including machine name) is misleading.
- there's a residual Relationship to the "Resource Type" taxonomy term on block_2
- there are extra displays, block_1 and page_1, that aren't referenced anywhere and may cause confusion on the block placement interfaces, or result in an accidental "list of all content" that the site builder did not intend to make available to all.

**Comment by noahwsmith** [comment]
I believe #11 addresses this issue, and trying to change things in a smaller way outside of that comprehensive update will cause more problems than it solves. I recommend we try to get that finished and merged.

Re "while we're at it" - these seem like minor annoyances that will be addressed when this whole process is replaced by the new https://github.com/Islandora/islandora-starter-site/ - is it worth changing any of that in the interim?
